### ISSUE TITLE
Logo has minor glitches

### ISSUE THREAD

**Issue by Taig** [typelevel/typelevel.github.com#125]
When watching closely, you can see that the edges of the symbol aren't properly aligned everywhere. It caught my eye when I saw the twitter version of the logo.

Here is a zoomed in screenshot that highlights the problem better: 
![Screenshot](https://cloud.githubusercontent.com/assets/567857/19354643/c89865f8-9167-11e6-8b97-699a33221e18.png)

**Comment by larsrh** [comment]
Interesting, good catch. Anybody who could volunteer fixing this?

**Comment by Taig** [comment]
I'll submit a PR over the weekend

**Comment by larsrh** [comment]
Thank you!

**Comment by killnicole** [comment]
Hey, I fixed that earlier, let me dig up the proper version...

**Comment by killnicole** [comment]
Here you go! [https://drive.google.com/file/d/0Bz8M1177BU3xdU9rVTNMVDdIV2c/view?usp=sharing](url)

**Comment by larsrh** [comment]
Excellent, thank you @killnicole!

@Taig, I'd still appreciate a PR replacing the various formats in the logo. Would be super cool if you could do that.

**Comment by Taig** [comment]
Gnaah, I've seen @killnicole's comment too late and already recreated the logo.

I'd appreciate if you could have a look at [my version](https://github.com/typelevel/typelevel.github.com/compare/development...Taig:logo-glitch?expand=1) and check if I messed anything up.

I upscaled the SVG to work with an integer pixel grid and got rid off the decimals, cleaned up the SVG code and downscaled the twitter png to 400x400px as suggested in their docs.

**Comment by killnicole** [comment]
@Taig @larsrh Yes, that looks fine to me! Thanks, guys!
