### ISSUE TITLE
Terrible font contrast. 

### ISSUE THREAD

**Issue by optician** [typelevel/typelevel.github.com#222]
It's of course subjective but the current color is a pain for eyes. Below is a screenshot where current font is on the right side and updated (I'm forced to do it every time) on the left.

![image](https://user-images.githubusercontent.com/3683866/42554433-8e1df5ca-84ed-11e8-803d-db7fe5c71949.png)

**Comment by larsrh** [comment]
Thanks for taking the time to report this. I've created #223, where a preview should appear soon.
