### ISSUE TITLE
Website build fails even inside Docker container.

### ISSUE THREAD

**Issue by tpolecat** [typelevel/typelevel.github.com#251]
I can't build the website locally or via the docker container. I get `You must use Bundler 2 or greater with this lockfile.`

**Comment by larsrh** [comment]
After poking around I now vaguely remember what the problem may be. Try the following: in the `Gemfile.lock`, remove the last two lines that say essentially "bundled with 2". This should do the trick.

**Comment by rossabaker** [comment]
Docker is gone.  The devshell is a solution for those of us who don't know how to Ruby.
