### ISSUE TITLE
merge upstream changes from Scala CoC

### ISSUE THREAD

**Issue by SethTisue** [typelevel/typelevel.github.com#268]
the following PRs making small adjustments to the Scala CoC have been merged:

* https://github.com/scala/scala-lang/pull/1079
* https://github.com/scala/scala-lang/pull/1082

I suggest that you adopt these changes in this repo as well.

**Comment by SethTisue** [comment]
@rossabaker (iirc, you had said you'd take this on?)

**Comment by rossabaker** [comment]
Yes, I will.

**Comment by SethTisue** [comment]
ping

**Comment by rossabaker** [comment]
Yes. Thanks for catching this.
