### ISSUE TITLE
Clarify "community venues" in the Code of Conduct

### ISSUE THREAD

**Issue by kpfell** [typelevel/typelevel.github.com#32]
The current Code of Conduct states,
> We expect participants to follow these rules at all community venues (including online venues) and social events associated with the community.

We should clarify which venues and events this line refers to--the Github repos? Google Group? IRC channel? Other places not listed on the "About" page? What venues, specifically, fall under the Typelevel umbrella? We should provide a comprehensive list of (online _and_ offline) venues within the Code of Conduct itself.

Or, alternatively, if we created this list as a separate page within the website--then linked to it from the Code of Conduct--it would be helpful not only in enforcing the Code of Conduct, but in serving as a place to point newcomers who are seeking assistance.

**Comment by adelbertc** [comment]
Looks like this is done via #53
