### ISSUE TITLE
Clarify "community staff" in the Code of Conduct

### ISSUE THREAD

**Issue by kpfell** [typelevel/typelevel.github.com#33]
It would be useful to list who, specifically, counts as a "member of the community staff." 

There's a link to the info@typelevel.org address, but I can see that being problematic if, for example, someone wanted to report a person who's well-known in the community. Without knowing who has access to the info@typelevel.org address, the reporter couldn't be certain that the person they're reporting wouldn't see the message first and retaliate.

That's problematic if the goal is to empower people to stop inappropriate behavior.

**Comment by adelbertc** [comment]
Looks like this is done via #54
