### ISSUE TITLE
Typelevel.scala branding

### ISSUE THREAD

**Issue by rossabaker** [typelevel/typelevel.github.com#349]
That sounds like the old compiler fork, or a non-existent domain.  Aren't we just Typelevel?

**Comment by jducoeur** [comment]
On the one hand, I agree; OTOH, this is already the case in the old site.  We should think about redoing that, but it's no worse than the existing site, so IMO not a blocker.

(I suspect we should come up with some labels representing issue priority, but I'm not inclined to yak-shave that too much right now.)

**Comment by rossabaker** [comment]
Well, it was easy.
