### ISSUE TITLE
Are any of the "abouts" more important than the others?

### ISSUE THREAD

**Issue by rossabaker** [typelevel/typelevel.github.com#364]
There are three on the home page in the reboot, as opposed to six on the current site.  It's trivial to put all six on the home page, but then the "about" page doesn't really add much.

**Comment by jducoeur** [comment]
It's a good question.  I don't have a *passionate* opinion about which ones show up on the home page -- I'd probably go with "Functional", "Friendly" and "Open Source", but I could probably argue for any of them.  I'd say choose three for now, and we can later have the conversation about whether it's worth having the separate "About" page.  (Which I think doesn't currently add much, but I want to go into a *lot* more detail in the medium term -- probably an entire linked page from each of these boxes.)

**Comment by rossabaker** [comment]
I don't think it would look terrible if we did all six on the home page, if we don't want to choose.  They've always been there.

**Comment by jducoeur** [comment]
Fair point -- in that case, probably makes sense to just put them in, and we can always adjust later.
