### ISSUE TITLE
Style issues on blog post(s)

### ISSUE THREAD

**Issue by jducoeur** [typelevel/typelevel.github.com#391]
A reader pointed out that the "formulas" in [this blog entry](https://typelevel.org/blog/2013/06/24/deriving-instances-1.html) don't look correct.  I don't know what it originally looked like, but I think he's correct -- in particular, the section "Abstracting All the Things" probably isn't right.

Doing a quick inspection, two issues jump out at me:

* There's a `side-note` style on a couple of paragraphs, which currently isn't doing anything.  We should figure out what it is *supposed* to look like, and improve that.
* Probably more importantly: there are some strings in there that are clearly supposed to be showing up as category theory math, that are just being rendered plain.  Examples include `$*$`, `$* \rightarrow *$`, `$\circ$`, `$\oplus$`, `$s_1, s_2,$`.  It's pretty clear that those dollar signs are delimiting spans that should be rendering as code, with things like `\oplus` rendering as symbols.  Was there some sort of post-processing step that we've lost, which was dealing with those?

This might get split into two separate bugs, to make resolution and tracking easier, once we've investigated a little and have a better idea of what's going on here.

**Comment by rossabaker** [comment]
It's MathJax.  I think I know how to fix it.
