### ISSUE TITLE
RSS feed for blog

### ISSUE THREAD

**Issue by jducoeur** [typelevel/typelevel.github.com#392]
Calling this a "bug" is a bit borderline, but it's a regression from the previous version so I think it's appropriate.  The blog should have an RSS feed, preferably at the same URL (https://typelevel.org/blog/feed.rss) as the old one.

It isn't clear offhand where the old feed came from.  Was it generated in post-processing?  Did it somehow come out of the server?

**Comment by alexandru** [comment]
The old feed is just a Jekyll generated file that's pretty straightforward:

https://github.com/typelevel/typelevel.github.com/blob/9c2be08b3217ca6c1a9a65e3832ab47131e8f5fb/blog/feed.rss

Alternatively, you could use a plugin. The following looks nice, but note that it generates Atom feeds, and the old one was RSS 2.0:

https://github.com/jekyll/jekyll-feed
