### ISSUE TITLE
Add RSS feed

### ISSUE THREAD

**Issue by S11001001** [typelevel/typelevel.github.com#48]
It would be nice to have an RSS feed for the blog.  I assume we can't use Jekyll plugins; can we flip a switch in github pages or something?

[Maybe this.](https://github.com/snaptortoise/jekyll-rss-feeds)

**Comment by larsrh** [comment]
There is one, see [feed.rss](https://github.com/typelevel/typelevel.github.com/blob/master/blog/feed.rss). It might be useful to declare it as a HTML `link` element everywhere on the site, though. (So far, only on `/blog`.)

**Comment by S11001001** [comment]
@larsrh Thanks!
