### ISSUE TITLE
Simplify build

### ISSUE THREAD

**Issue by larsrh** [typelevel/typelevel.github.com#64]
* let Jekyll build CSS files (reference: http://markdotto.com/2014/09/25/sass-and-jekyll/)
* use Bundler to install Jekyll (reference: https://github.com/scala/scala.github.com)

**Comment by propensive** [comment]
It took me about an hour to get this working, for a collection of tools that looked like they were designed to make this trivial. The cynic in me suspects it is trivial for 50% of people, or anyone using OSX...

Would an alternative be to provide an off-the-shelf Docker instance with all of this stuff installed? (I haven't checked, but I suspect one exists...)

**Comment by SethTisue** [comment]
@propensive what was the hard part?

**Comment by larsrh** [comment]
Fixed by #84.
