### ISSUE TITLE
compiler-verified blog code

### ISSUE THREAD

**Issue by ceedubs** [typelevel/typelevel.github.com#78]
It would be nice if [tut](https://github.com/tpolecat/tut) (or something similar) were used to verify that the code examples in blog posts actually compiles and (when relevant) produces the expected output.

cc @tpolecat

**Comment by larsrh** [comment]
This is currently blocking on tpolecat/tut#91 and @nebasuke.

**Comment by tpolecat** [comment]
Yeah once we get the workflow figured out I will be happy to go back and update the existing blog posts.

**Comment by larsrh** [comment]
Fixed by #119.
